/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosissocer;

import clases.Jornada;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static proyectosissocer.frmNuevoEquipo.pNomCampeonatoFixture;
import static proyectosissocer.frmPrincipal.desktop;
import static proyectosissocer.frmPrincipal.gestor;

import vistas.vistaEncuentrosModoLiga;

/**
 *
 * @author Geiner Saucedo
 */
public class frmFixtures extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAdmCampeonatos
     */
    public static int pNumFecha;
    public static int pIdEncuentro;
    public static String pNomCampeonato;
    
    
    public frmFixtures() {
        initComponents();
        cbCampeonato.removeAllItems();
        cbCampeonato.addItem("Seleccionar");
        for(int i=0;i<frmPrincipal.lista.size();i++){
            cbCampeonato.addItem(frmPrincipal.lista.get(i).getNombreCampeonato());
        }   
        if(pNomCampeonatoFixture != null) cbCampeonato.setSelectedItem(pNomCampeonatoFixture);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnFecha = new javax.swing.JButton();
        cbCampeonato = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEcuentros = new javax.swing.JTable();
        btnRegistrarResultado = new javax.swing.JButton();
        cbNumFecha = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnSeleccionarCampeonato = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Fixtures");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fixture");

        btnFecha.setText("Seleccionar");
        btnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActionPerformed(evt);
            }
        });

        cbCampeonato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        jLabel9.setText("Campeonato:");

        tblEcuentros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Local", "Visita"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEcuentros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblEcuentros);
        if (tblEcuentros.getColumnModel().getColumnCount() > 0) {
            tblEcuentros.getColumnModel().getColumn(2).setResizable(false);
        }

        btnRegistrarResultado.setText("Registrar Resultado");
        btnRegistrarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRegistrarResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        cbNumFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        jLabel10.setText("Fecha");

        btnSeleccionarCampeonato.setText("Seleccionar");
        btnSeleccionarCampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarCampeonatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbNumFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSeleccionarCampeonato, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(btnFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarCampeonato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbNumFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarResultadoActionPerformed
        int column = 0;
        int row = tblEcuentros.getSelectedRow();
               
        if(cbCampeonato.getSelectedItem().toString().equals("Seleccionar") || cbNumFecha.getSelectedItem().toString().equals("Seleccionar") || row == -1){
            JOptionPane.showMessageDialog(null, "Seleccione un encuentro");
            return;
        }
        if(!tblEcuentros.getModel().getValueAt(row, 7).toString().equals("Pendiente")){
            JOptionPane.showMessageDialog(null, "El encuentro ya fue registrado");
            return;        
        }
        pIdEncuentro = Integer.parseInt(tblEcuentros.getModel().getValueAt(row, column).toString());        
        pNumFecha = Integer.parseInt(cbNumFecha.getSelectedItem().toString());
        pNomCampeonato = cbCampeonato.getSelectedItem().toString();
        
        frmEncuentro frm=new frmEncuentro();
        desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_btnRegistrarResultadoActionPerformed

    private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed
        // TODO add your handling code here:
        ArrayList<Jornada> ObjLista = gestor.buscarCampeonato(cbCampeonato.getSelectedItem().toString()).getObjFixture().getListaJornadas();
        
        
        for (Jornada j : ObjLista) {
            if(j.getNumFecha()== Integer.parseInt(cbNumFecha.getSelectedItem().toString())){
                vistaEncuentrosModoLiga ObjVista = new vistaEncuentrosModoLiga();
                ObjVista.setObjListaEncuentro(j.getListaEncuentro());
                tblEcuentros.setModel(ObjVista);
                tblEcuentros.updateUI();
            }
        }
        //tblEcuentros.setModel(gestor.buscarCampeonato(cbCampeonato.getSelectedItem().toString()).getObjFixture().getListaJornadas());
    }//GEN-LAST:event_btnFechaActionPerformed

    private void btnSeleccionarCampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarCampeonatoActionPerformed
        // TODO add your handling code here:
        cbNumFecha.removeAllItems();
        ArrayList<Jornada> ListaJornada = gestor.buscarCampeonato(cbCampeonato.getSelectedItem().toString()).getObjFixture().getListaJornadas();
        for(int i=0;i<ListaJornada.size();i++){
            cbNumFecha.addItem(String.valueOf(ListaJornada.get(i).getNumFecha()));
        }
            
    }//GEN-LAST:event_btnSeleccionarCampeonatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecha;
    private javax.swing.JButton btnRegistrarResultado;
    private javax.swing.JButton btnSeleccionarCampeonato;
    private javax.swing.JComboBox<String> cbCampeonato;
    private javax.swing.JComboBox<String> cbNumFecha;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEcuentros;
    // End of variables declaration//GEN-END:variables
}
